export const reviewsSection = {
  tag: "Customer Reviews",
  title: "What Our Customers Say",
  subtitle: "Real feedback from customers who order regularly from Ulavapadu Mangoes.",

  stats: [
    { label: "Happy Customers", value: "500+" },
    { label: "Average Rating", value: "4.9" },
    { label: "Orders Delivered", value: "1000+" },
    { label: "Satisfaction", value: "100%" },
  ],

  reviews: [
    {
      id: "rev_001",
      rating: 5,
      comment: "Premium Banganapalli mangoes arrived fresh and perfectly ripened.",
      name: "Lakshmi Devi",
      location: "Rajahmundry",
    },
    {
      id: "rev_002",
      rating: 5,
      comment: "Totapuri mangoes were ideal for juice. Good quality and fair pricing.",
      name: "Venkat Rao",
      location: "Hyderabad",
    },
    {
      id: "rev_003",
      rating: 5,
      comment: "Rasalu mangoes were very juicy and sweet. Family loved them.",
      name: "Padma Kumari",
      location: "Vijayawada",
    },
    {
      id: "rev_004",
      rating: 4,
      comment: "Raw mango batch was perfect for avakaya pickle making.",
      name: "Suresh Kumar",
      location: "Kakinada",
    },
    {
      id: "rev_005",
      rating: 5,
      comment: "Mango pulp quality was excellent and delivery was on time.",
      name: "Anitha Reddy",
      location: "Bangalore",
    },
    {
      id: "rev_006",
      rating: 5,
      comment: "Ordered mango pickle and jam together. Both tasted authentic.",
      name: "Ravi Prasad",
      location: "Chennai",
    },
    {
      id: "rev_007",
      rating: 5,
      comment: "Consistent quality every time. Good support on WhatsApp as well.",
      name: "Meena Sharma",
      location: "Vizag",
    },
    {
      id: "rev_008",
      rating: 5,
      comment: "Been ordering for two seasons now. Always reliable and fresh stock.",
      name: "Prakash Reddy",
      location: "Guntur",
    },
    {
      id: "rev_009",
      rating: 4,
      comment: "Packaging was neat and fruits reached without damage.",
      name: "Kavitha Devi",
      location: "Nellore",
    },
    {
      id: "rev_010",
      rating: 5,
      comment: "Bulk order for family event was handled smoothly.",
      name: "Ramesh Kumar",
      location: "Tirupati",
    },
    {
      id: "rev_011",
      rating: 5,
      comment: "Good taste, fair prices, and simple ordering experience.",
      name: "Sita Lakshmi",
      location: "Ongole",
    },
    {
      id: "rev_012",
      rating: 5,
      comment: "Fast delivery and exactly the same products as shown in menu.",
      name: "Narasimha Rao",
      location: "Eluru",
    },
  ],
};
